os:
  - linux

language: cpp

install:
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install mpich libmpich-dev; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install libomp-dev libtbb-dev; fi

before_script:
  - mkdir build
  - cd build
script:
  - cmake ..
notifications:
  email: false
