language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
script:
- git submodule update --init --recursive
  - cmake ..
  - cmake --build . --config -j4
  - cd ..
  - export OMP_NUM_THREADS=4
  - source scripts/run.sh
notifications:
  email: false
